### ISSUE TITLE
main window refuses to cooperate

### ISSUE THREAD

**Issue by sergpolly** [nvictus/graal-docker#1]
we tried running python `main_window.py`  inside your docker image, but it refuses to cooperate. Does any of the errors/warnings make sense or seems familiar to you? Does it make sense to rebuild that image locally?

```
root@76fc7d444f56:/GRAAL# python main_window.py 
Gtk-Message: Failed to load module "canberra-gtk-module"

(python:25): GLib-GObject-WARNING **: gsignal.c:2641: instance '0x2a439c0' has no handler with id '55'
You selected: /data/S1


(python:25): Gtk-WARNING **: Attempting to store changes into `/root/.local/share/recently-used.xbel', but failed: Failed to create file ?/root/.local/share/recently-used.xbel.ALLG5Y?: No such file or directory

(python:25): Gtk-WARNING **: Attempting to set the permissions of `/root/.local/share/recently-used.xbel', but failed: No such file or directory
Fasta file: /data/fasta/s_cerevisiae.fsa


(python:25): Gtk-WARNING **: Attempting to store changes into `/root/.local/share/recently-used.xbel', but failed: Failed to create file ?/root/.local/share/recently-used.xbel.99G64Y?: No such file or directory

(python:25): Gtk-WARNING **: Attempting to set the permissions of `/root/.local/share/recently-used.xbel', but failed: No such file or directory
start filtering
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/miniconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "main_window.py", line 89, in run
    pyramid = pyr.build_and_filter(self.base_folder, self.size_pyramid, self.factor)
  File "/GRAAL/pyramid_sparse.py", line 65, in build_and_filter
    current_abs_fragments_contacts, pyramid_0)
  File "/GRAAL/pyramid_sparse.py", line 574, in remove_problematic_fragments
    level = pyramid["0"]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/feedstock_root/build_artefacts/h5py_1497016237490/work/h5py-2.7.0/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/feedstock_root/build_artefacts/h5py_1497016237490/work/h5py-2.7.0/h5py/_objects.c:2804)
  File "/miniconda2/lib/python2.7/site-packages/h5py/_hl/group.py", line 169, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/feedstock_root/build_artefacts/h5py_1497016237490/work/h5py-2.7.0/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/feedstock_root/build_artefacts/h5py_1497016237490/work/h5py-2.7.0/h5py/_objects.c:2804)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/feedstock_root/build_artefacts/h5py_1497016237490/work/h5py-2.7.0/h5py/h5o.c:3740)
KeyError: "Unable to open object (Object '0' doesn't exist)"
```

**Comment by nvictus** [comment]
Weird.

Some files it made might be broken from a failed run. Try deleting everything but the `.txt` and fasta files in `examples`. Make sure to do the steps in the right order... I think "Load data" first; choose the folder `S1` or `tricho_qm6a`. Then "Load fasta file"; choose the file. Then Build Pyramid. Then Load Pyramid. Then GRAAL.

Also, does your docker require root privileges to run? Try running [without root](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04#step-2-—-executing-the-docker-command-without-sudo-optional).

Otherwise, maybe try rebuilding locally.

**Comment by sergpolly** [comment]
We were using sudo docker all the way, - tried your image and tried rebuilding, tried erasing everything but original info from `examples`; I even tried installing `canberra-gtk-module` inside the image; manually creating `/root/.local/share/recently-used.xbel` (it is being written, when manually created) - nothing seems to work...

I just added my user to the `docker` group and re-tried - does not seem to work either.
Would it makes sense to rebuild again without using `sudo docker` or it shouldn't affect anything?

new error message:
```
root@8a7bf7a680c3:/GRAAL# python main_window.py 
Gtk-Message: Failed to load module "canberra-gtk-module"

(python:18): GLib-GObject-WARNING **: gsignal.c:2641: instance '0x31581c0' has no handler with id '55'
You selected: /data/S1


(python:18): Gtk-WARNING **: Attempting to store changes into `/root/.local/share/recently-used.xbel', but failed: Failed to create file ?/root/.local/share/recently-used.xbel.ED644Y?: No such file or directory

(python:18): Gtk-WARNING **: Attempting to set the permissions of `/root/.local/share/recently-used.xbel', but failed: No such file or directory
Fasta file: /data/fasta/s_cerevisiae.fsa


(python:18): Gtk-WARNING **: Attempting to store changes into `/root/.local/share/recently-used.xbel', but failed: Failed to create file ?/root/.local/share/recently-used.xbel.F4224Y?: No such file or directory

(python:18): Gtk-WARNING **: Attempting to set the permissions of `/root/.local/share/recently-used.xbel', but failed: No such file or directory
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/miniconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "main_window.py", line 89, in run
    pyramid = pyr.build_and_filter(self.base_folder, self.size_pyramid, self.factor)
  File "/GRAAL/pyramid_sparse.py", line 36, in build_and_filter
    build(base_folder, init_size_pyramid, factor, min_bin_per_contig,)
  File "/GRAAL/pyramid_sparse.py", line 170, in build
    nfrags = init_frag_list(fragments_list,current_frag_list)
  File "/GRAAL/pyramid_sparse.py", line 338, in init_frag_list
    contig_name = data[1]
IndexError: list index out of range
```
